FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y \
        bind9-dnsutils \
        bind9-host \
        bind9-utils \
        iputils-ping \
        jq \
        less \
        net-tools \
        netcat-openbsd \
        rsync \
        sudo \
        tcpdump \
        unzip \
        vim \
        xz-utils \
        iproute2
